### ISSUE TITLE
read file >2GB,doesn't show report

### ISSUE THREAD

**Issue by ann-ibm** [sine-io/cosbench-sineio#45]
When each chunk file size >2GB, read the status show complete, log has no error, but can't get any detail report

**Comment by ann-ibm** [comment]
```
<?xml version="1.0" encoding="UTF-8" ?>
<workload name="proxy-3G-1-01-starter-zy-useast1" description="sample benchmark for s3">
  <storage type="siov2" config="accesskey=<key>;secretkey=<key>;endpoint=https://s3.us-east-1.amazonaws.com;path_style_access=true;no_verify_ssl=true;aws_region=us-east-1;timeout=300000"/>
  <workflow>
    <workstage name="main">
      <work name="main" workers="1" runtime="600" interval="10">
        <operation type="read" ratio="100" config="hashCheck=False;cprefix=zytest;csuffix=-1250000000;containers=u(1,10);objects=u(3,3)" />
      </work>
    </workstage>
  </workflow>
</workload>
```

**Comment by kisscelia** [comment]
i will try to reproduce it in my environment, please wait, thank you.

**Comment by kisscelia** [comment]
logs:
```
2024-07-24 00:16:34,411 [INFO] [Log4jLogManager] - will append log to file /root/cos/cosbench-0.5.0.0-sineio/log/mission/M4E399504B1.log
2024-07-24 00:16:34,412 [DEBUG] [Log4jLogManager] - log level has been set to DEBUG
2024-07-24 00:16:34,437 [DEBUG] [SIOStorageV2] - initialize S3 client with storage config: {logging=true}
2024-07-24 00:16:34,458 [DEBUG] [SIOStorageV2] - S3 client has been initialized
2024-07-24 00:16:34,479 [DEBUG] [AuthAgent] - begin to login, will attempt 1 times
2024-07-24 00:16:34,482 [DEBUG] [AuthAgent] - input auth context is {logging=false, caching=false} with caching=false
2024-07-24 00:16:34,482 [DEBUG] [AuthAgent] - worker 1 has been successfully authed
2024-07-24 00:16:34,690 [INFO] [NoneStorage] - performing GET(get-object) at /zytest4-1250000000/myobjects3
2024-07-24 00:16:54,915 [DEBUG] [WorkerContext] - Worker[1] : blank snapshot is generated.
2024-07-24 00:17:04,924 [DEBUG] [WorkerContext] - Worker[1] : blank snapshot is generated.
2024-07-24 00:17:14,935 [DEBUG] [WorkerContext] - Worker[1] : blank snapshot is generated.
```

**Comment by kisscelia** [comment]
test code:

aws-sdk-java: --- passed
```
package com.sineio.s3api;


import java.io.File;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.io.OutputStream;

import org.apache.commons.io.IOUtils;

import com.amazonaws.ClientConfiguration;
import com.amazonaws.auth.AWSCredentials;
import com.amazonaws.auth.AWSStaticCredentialsProvider;
import com.amazonaws.auth.BasicAWSCredentials;
import com.amazonaws.client.builder.AwsClientBuilder.EndpointConfiguration;
import com.amazonaws.regions.Regions;
import com.amazonaws.services.s3.AmazonS3;
import com.amazonaws.services.s3.AmazonS3ClientBuilder;
import com.amazonaws.services.s3.model.S3Object;

/**
 * S3 client via aws-sdk-java
 *
 */
public class App {
    public static void main( String[] args ) {
    	
    	String accessKey = "xxx";
    	String secretKey = "xxx";
    	String endpoint = "http://ip:port";
    	boolean pathStyleAccess = true;
    	
    	ClientConfiguration defaultClientConfiguration = new ClientConfiguration();
		// Set connection timeout for initially establishing a connection.
		defaultClientConfiguration.setConnectionTimeout(60000);
		// Set socket timeout for data to be transferred.
		defaultClientConfiguration.setSocketTimeout(60000);
		// Set max connections.
		defaultClientConfiguration.setMaxConnections(50);
		// use expect continue HTTP/1.1 header.
		defaultClientConfiguration.withUseExpectContinue(false);

		AWSCredentials myCredentials = new BasicAWSCredentials(accessKey, secretKey);
		EndpointConfiguration myEndpoint = new EndpointConfiguration(endpoint, "");

		AmazonS3 client = AmazonS3ClientBuilder.standard()
				.withCredentials(new AWSStaticCredentialsProvider(myCredentials))
				.withClientConfiguration(defaultClientConfiguration)
				.withEndpointConfiguration(myEndpoint)
				.withPathStyleAccessEnabled(pathStyleAccess)
				.withRegion(Regions.US_EAST_1)
				.build();
		
		InputStream stream = null;
		OutputStream os = null;
		
		try {
			S3Object s3Obj = client.getObject("20240729-1", "w1-1gib-1");
	        stream = s3Obj.getObjectContent();
	        
	        File myFile = new File("./testfilev1");
            os = new FileOutputStream(myFile);
            System.out.println("copying object...");
        	long count = IOUtils.copyLarge(stream, os);
        	System.out.println("length: " + count);
		} catch (Exception e) {
			System.out.println("v1 Exception: " + e.getStackTrace());
		} finally {
			IOUtils.closeQuietly(stream);
			IOUtils.closeQuietly(os);
		}
    }
    
}
```

**Comment by kisscelia** [comment]
test code:

aws-sdk-java-v2: --- failed
```
package com.sineio.s3api;


import java.io.InputStream;
import java.net.URI;
import java.time.Duration;

import java.io.File;
import java.io.FileOutputStream;
import java.io.OutputStream;

import org.apache.commons.io.IOUtils;

import software.amazon.awssdk.auth.credentials.AwsBasicCredentials;
import software.amazon.awssdk.auth.credentials.StaticCredentialsProvider;
import software.amazon.awssdk.core.ResponseBytes;
import software.amazon.awssdk.http.apache.ApacheHttpClient;
import software.amazon.awssdk.regions.Region;
import software.amazon.awssdk.services.s3.S3Client;
import software.amazon.awssdk.services.s3.S3Configuration;
import software.amazon.awssdk.services.s3.model.GetObjectRequest;
import software.amazon.awssdk.services.s3.model.GetObjectResponse;


/**
 * S3 client via aws-sdk-java-v2
 *
 */
public class AppV2 {
	
    public static void main( String[] args ) {
    	String accessKey = "xxx";
    	String secretKey = "xxx";
    	String endpoint = "http://ip:port";
    	boolean pathStyleAccess = true;
    	
		AwsBasicCredentials awsCreds = AwsBasicCredentials.create(accessKey, secretKey);
		S3Configuration s3Config = S3Configuration.builder().pathStyleAccessEnabled(pathStyleAccess).build();

		ApacheHttpClient.Builder httpClientBuilder = ApacheHttpClient.builder()
				// max connections.
				.maxConnections(50)
				// Set socket timeout for data to be transferred.
				.socketTimeout(Duration.ofMillis(60000))
				// Set connection timeout for initially establishing a connection.
				.connectionTimeout(Duration.ofMillis(60000))
				// disable expect continue for HTTP/1.1.
				.expectContinueEnabled(false);
		
		S3Client client = S3Client.builder()
				.credentialsProvider(StaticCredentialsProvider.create(awsCreds))
				.endpointOverride(URI.create(endpoint))
				.region(Region.US_EAST_1)
				.serviceConfiguration(s3Config)
				.httpClient(httpClientBuilder.build())
				.build();
		
		InputStream stream = null;
		OutputStream os = null;
		
        try {
        	
        	GetObjectRequest.Builder getObjectRequest = GetObjectRequest.builder()
    				.bucket("20240729-1")
    				.key("w1-2gib-1");
    		
    		ResponseBytes<GetObjectResponse> objectBytes = client.getObjectAsBytes(getObjectRequest.build());
    		stream = objectBytes.asInputStream();
    		
        	File myFile = new File("./testfilev2");
            os = new FileOutputStream(myFile);
            System.out.println("copying object...");
        	long count = IOUtils.copyLarge(stream, os);
        	System.out.println("length: " + count);
            
		} catch (Exception e) {
			System.out.println("v2 Exception: " + e.getStackTrace());
		} finally {
			IOUtils.closeQuietly(stream);
			IOUtils.closeQuietly(os);
		}
    }
}
```

error:
```
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Unknown Source)
	at java.io.ByteArrayOutputStream.grow(Unknown Source)
	at java.io.ByteArrayOutputStream.ensureCapacity(Unknown Source)
	at java.io.ByteArrayOutputStream.write(Unknown Source)
	at software.amazon.awssdk.utils.IoUtils.toByteArray(IoUtils.java:48)
	at software.amazon.awssdk.core.sync.ResponseTransformer.lambda$toBytes$3(ResponseTransformer.java:175)
	at software.amazon.awssdk.core.sync.ResponseTransformer$$Lambda$296/293474277.transform(Unknown Source)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler$HttpResponseHandlerAdapter.transformResponse(BaseSyncClientHandler.java:225)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler$HttpResponseHandlerAdapter.handle(BaseSyncClientHandler.java:213)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleSuccessResponse(CombinedResponseHandler.java:99)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleResponse(CombinedResponseHandler.java:75)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handle(CombinedResponseHandler.java:60)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handle(CombinedResponseHandler.java:41)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:50)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:38)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:72)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:42)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:78)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:40)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:55)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:39)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage2.executeRequest(RetryableStage2.java:93)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage2.execute(RetryableStage2.java:56)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage2.execute(RetryableStage2.java:36)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:56)
	at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:36)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.executeWithTimer(ApiCallTimeoutTrackingStage.java:80)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:60)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:42)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallMetricCollectionStage.execute(ApiCallMetricCollectionStage.java:50)
```

**Comment by kisscelia** [comment]
![image](https://github.com/user-attachments/assets/fe007014-b931-4b17-a5ef-a06f8a6cb860)

test code:

aws-sdk-java-v2: --- pass
```
package com.sineio.s3api;


import java.io.InputStream;
import java.net.URI;
import java.time.Duration;

import java.io.File;
import java.io.FileOutputStream;
import java.io.OutputStream;

import org.apache.commons.io.IOUtils;

import software.amazon.awssdk.auth.credentials.AwsBasicCredentials;
import software.amazon.awssdk.auth.credentials.StaticCredentialsProvider;
import software.amazon.awssdk.core.ResponseBytes;
import software.amazon.awssdk.http.apache.ApacheHttpClient;
import software.amazon.awssdk.regions.Region;
import software.amazon.awssdk.services.s3.S3Client;
import software.amazon.awssdk.services.s3.S3Configuration;
import software.amazon.awssdk.services.s3.model.GetObjectRequest;
import software.amazon.awssdk.services.s3.model.GetObjectResponse;


/**
 * S3 client via aws-sdk-java-v2
 *
 */
public class AppV2 {
	
    public static void main( String[] args ) {
    	String accessKey = "xxx";
    	String secretKey = "xxx";
    	String endpoint = "http://ip:port";
    	boolean pathStyleAccess = true;
    	
		AwsBasicCredentials awsCreds = AwsBasicCredentials.create(accessKey, secretKey);
		S3Configuration s3Config = S3Configuration.builder().pathStyleAccessEnabled(pathStyleAccess).build();

		ApacheHttpClient.Builder httpClientBuilder = ApacheHttpClient.builder()
				// max connections.
				.maxConnections(50)
				// Set socket timeout for data to be transferred.
				.socketTimeout(Duration.ofMillis(60000))
				// Set connection timeout for initially establishing a connection.
				.connectionTimeout(Duration.ofMillis(60000))
				// disable expect continue for HTTP/1.1.
				.expectContinueEnabled(false);
		
		S3Client client = S3Client.builder()
				.credentialsProvider(StaticCredentialsProvider.create(awsCreds))
				.endpointOverride(URI.create(endpoint))
				.region(Region.US_EAST_1)
				.serviceConfiguration(s3Config)
				.httpClient(httpClientBuilder.build())
				.build();
		
		InputStream stream = null;
		OutputStream os = null;
		
        try {
        	
        	GetObjectRequest.Builder getObjectRequest = GetObjectRequest.builder()
    				.bucket("20240729-1")
    				.key("w1-2gib-1");
        	
        	stream = client.getObject(getObjectRequest.build());
    		
        	File myFile = new File("./testfilev2");
            os = new FileOutputStream(myFile);
            System.out.println("copying object...");
        	long count = IOUtils.copyLarge(stream, os);
        	System.out.println("length: " + count);
            
		} catch (Exception e) {
			System.out.println("v2 Exception: " + e.getStackTrace());
		} finally {
			IOUtils.closeQuietly(stream);
			IOUtils.closeQuietly(os);
		}
    }
}
```

**Comment by kisscelia** [comment]
fixed:
![image](https://github.com/user-attachments/assets/bdf27d68-10d7-4397-bf8d-6312c2b9d6d0)
